### PR TITLE
update: formatting README to make it more readable

### PR DESCRIPTION
**Pull request by ayushanand18**
## Overview
Formatting the README to make it more readable and contributor friendly.

## Changes Introduced
* Introduced heading for 'Clay'.
* Add PYPI badge to indicate version and project link.
* Add headings for Documentation and Installation.

Thanks!

### CODE REVIEW

**Comment by ayushanand18** [comment]
cc @JeremyGrosser @eklitzke

**Comment by JeremyGrosser** [comment]
Neither of us has worked at Uber in a very long time and we no longer have commit access to this repository. As far as I know, Uber does not maintain the public version of this project anymore.

**Comment by ayushanand18** [comment]
> Neither of us has worked at Uber in a very long time and we no longer have commit access to this repository. As far as I know, Uber does not maintain the public version of this project anymore.

Gotcha. Thank you for the info and really sorry for pinging.

**Comment by rabbbit** [comment]
Agreed, the last change to the repo was in 2018, let's not update anything anymore.

There's probably a process to get the whole thing archived, but that's a separate conversation.

**Pull request closed without merging**
